---
- name: install mail server
  dnf:
    name:
      - postfix
      - mailx
    state: latest

- name: start postfix
  systemd:
    name: postfix
    state: started
    enabled: yes

- name: add script
  template: 
    src: templates/sendlog.sh.j2
    dest: /usr/local/bin/sendlog.sh
    owner: vagrant
    group: vagrant
    mode: "0755"  
