---
- name: install mail server
  dnf:
    name:
      - postfix
      - s-nail
    state: latest

- name: template mailrc
  template:
    src: templates/mailrc
    dest: /home/vagrant/.mailrc
    owner: root
    group: root
    mode: "0644"
 
- name: start postfix
  systemd:
    name: postfix
    state: started
    enabled: yes

- name: add script
  template: 
    src: templates/sendlog.sh.j2
    dest: /usr/local/bin/sendlog.sh
    owner: vagrant
    group: vagrant
    mode: "0755"  
